### ISSUE TITLE
[TODO] Stuff

### ISSUE THREAD

**Issue by Sunconure11** [Sunconure11/Farmers-Delight-Unofficial#1]
- [x] Make a functional fabric build for 1.18.2. Newer builds of the API get fucky with this mod.
- [ ] After that, make a build for quilt
- [ ] Display both the quilt and fabric builds to the appropriate devs for further distribution beyond this repo
